apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydemo-deployment
    #namespace: ingress-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydemo
  template:
    metadata:
      labels:
        app: mydemo
    spec:
      containers:
      - name: mydemo
        image:kanagarasu/mydemo-app:9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mydemo-service
    # namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app: mydemo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008

