name: Jekyll Build, Test, Docker Push & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Jekyll Site
    runs-on: ubuntu-latest
    outputs:
      site-dir: ${{ steps.set-output.outputs.dir }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Jekyll Site in Container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: _site

      - name: Validate HTML (Optional)
        run: |
          sudo apt-get install tidy -y
          find _site -name '*.html' -exec tidy -qe {} \;

      - name: Lint Markdown (Optional)
        run: |
         gem install mdl --user-install
         ~/.local/share/gem/ruby/3.2.0/bin/mdl .


  push:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - uses: actions/checkout@v4

        - name: Download build artifact
          uses: actions/download-artifact@v4
          with:
            name: jekyll-site
            path: _site

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and Push Docker Image
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: |
              ${{ secrets.DOCKER_USERNAME }}/mydemo-app:latest
              ${{ secrets.DOCKER_USERNAME }}/mydemo-app:${{ github.run_number }}
  deploy:
     name: Deploy on Self-Hosted Server
     runs-on: self-hosted
     needs: push
     steps:
       - name: Pull and Run Docker Container
         run: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/jekyll-site:${{ github.run_number }}
            docker stop jekyll-site || true
            docker rm jekyll-site || true
            docker run -d --name jekyll-site -p 80:80 ${{ secrets.DOCKER_USERNAME }}/jekyll-site:${{ github.run_number }}
